# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Evy < Formula
  desc "Evy is a simple programming language."
  homepage "https://evy.dev"
  version "0.0.109"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foxygoat/evy/releases/download/v0.0.109/evy_0.0.109_darwin_amd64.tar.gz"
      sha256 "81cf1a8e844dfeaa51b1fe147fa55af21aea85a20f52f775f39046a222d7d93e"

      def install
        bin.install "evy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foxygoat/evy/releases/download/v0.0.109/evy_0.0.109_darwin_arm64.tar.gz"
      sha256 "0f2aacbb765cd4ca7a9ece9d021945272a2b36fb3c565d9e65ab60af6c448708"

      def install
        bin.install "evy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foxygoat/evy/releases/download/v0.0.109/evy_0.0.109_linux_arm64.tar.gz"
      sha256 "ea2a51a93c89eb125e09abf07a9ee0de3d59a87caa0b40b3971502201a29d0cf"

      def install
        bin.install "evy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/foxygoat/evy/releases/download/v0.0.109/evy_0.0.109_linux_amd64.tar.gz"
      sha256 "d759c814911324c3fce559d4c1f9a30364685cf8eb226ba2466fa42be0403d57"

      def install
        bin.install "evy"
      end
    end
  end
end
