# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Evy < Formula
  desc "Evy is a simple programming language."
  homepage "https://evy.dev"
  version "0.0.124"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foxygoat/evy/releases/download/v0.0.124/evy_0.0.124_darwin_amd64.tar.gz"
      sha256 "d7241bb355d4f68d0bed122cc18b0b4d2261c7949b6549d6de0dad6c891c83b0"

      def install
        bin.install "evy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foxygoat/evy/releases/download/v0.0.124/evy_0.0.124_darwin_arm64.tar.gz"
      sha256 "168aa201a5c3f53e49de0160b44173b846e2abc0b4d762f05806707749fe4882"

      def install
        bin.install "evy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foxygoat/evy/releases/download/v0.0.124/evy_0.0.124_linux_arm64.tar.gz"
      sha256 "1b441e27f5301c2d8961e4a2841c89e0d701779a1a60653822c17d7e3514bed3"

      def install
        bin.install "evy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/foxygoat/evy/releases/download/v0.0.124/evy_0.0.124_linux_amd64.tar.gz"
      sha256 "d350e69c2401efe1cc5eaa2546159122732972315ee86912574fd68de389ab95"

      def install
        bin.install "evy"
      end
    end
  end
end
