# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Evy < Formula
  desc "Evy is a simple programming language."
  homepage "https://evy.dev"
  version "0.0.61"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foxygoat/evy/releases/download/v0.0.61/evy_0.0.61_darwin_amd64.tar.gz"
      sha256 "4f512793ca4c9581f8881da09edacc49ba085ff8d4c300bd96a8841dc77af9e8"

      def install
        bin.install "evy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foxygoat/evy/releases/download/v0.0.61/evy_0.0.61_darwin_arm64.tar.gz"
      sha256 "f6d34060bef5bf8256107987031de43a3ba1038753594a1028b7d6f01021509d"

      def install
        bin.install "evy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foxygoat/evy/releases/download/v0.0.61/evy_0.0.61_linux_arm64.tar.gz"
      sha256 "a6c29ee2193ac1e2313e03d7fe6087fdba5ffc65fc64b046221b73df808b0b23"

      def install
        bin.install "evy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/foxygoat/evy/releases/download/v0.0.61/evy_0.0.61_linux_amd64.tar.gz"
      sha256 "6a159816fbd5f5a66497bdaf3516da0e296259b287d41fab8ed76ed72b9a3999"

      def install
        bin.install "evy"
      end
    end
  end
end
